### ISSUE TITLE
Help required?

### ISSUE THREAD

**Issue by ChlorinePentoxide** [huynguyen7/Java-Alg#1]
Hey @huynguyen7 ,

A great collection of code, by the way. 
Is contributions accepted? Is there anything I can help with?

With regards,
ChlorinePentoxide

**Comment by huynguyen7** [comment]
Hey Chlorine,

I'm opening this repo just for the purpose of sharing knowledges. I don't tend to make it looks professional.
But I'm happy to see if there is more interesting algorithms contributed. You can fork this repo and start making pull request.

Thanks!
Huy
